# Generated by Django 2.2.12 on 2022-05-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('dtnascimento', models.DateField(verbose_name='Data Nascimento')),
                ('sexo', models.CharField(max_length=50, verbose_name='Sexo')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('complemento', models.CharField(max_length=30, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('celular', models.IntegerField(verbose_name='Celular')),
            ],
        ),
    ]
