# Generated by Django 2.2.12 on 2022-05-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(verbose_name='Matricula')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('dtnascimento', models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data Nascimento')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Não Definido', 'Não Definido')], max_length=50, verbose_name='Sexo')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('complemento', models.CharField(max_length=30, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('celular', models.IntegerField(verbose_name='Celular')),
                ('dtadmissao', models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data Admissão')),
                ('dtdemissao', models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data Demissao')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dtnascimento',
            field=models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data Nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Não Definido', 'Não Definido')], max_length=50, verbose_name='Sexo'),
        ),
    ]
