# Generated by Django 2.2.12 on 2022-05-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20220501_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticao', models.IntegerField(verbose_name='Repetições:')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Exercicio:')),
                ('tipoTreino', models.CharField(max_length=255, verbose_name='Tipo de Treino:')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição:')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Ficha:')),
                ('cliente', models.CharField(max_length=255, verbose_name='Cliente:')),
                ('funcionario', models.CharField(max_length=255, verbose_name='Funcionário:')),
                ('exercicio', models.CharField(max_length=255, verbose_name='Exercicio:')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(max_length=50, verbose_name='Bairro:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.IntegerField(verbose_name='Celular:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.IntegerField(verbose_name='CEP:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(max_length=30, verbose_name='Complemento:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dtnascimento',
            field=models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data Nascimento:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=150, verbose_name='Endereço:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(verbose_name='Número:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Não Definido', 'Não Definido')], max_length=50, verbose_name='Sexo:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(verbose_name='Telefone:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='bairro',
            field=models.CharField(max_length=50, verbose_name='Bairro:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='celular',
            field=models.IntegerField(verbose_name='Celular:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cep',
            field=models.IntegerField(verbose_name='CEP:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='complemento',
            field=models.CharField(max_length=30, verbose_name='Complemento:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.IntegerField(verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dtadmissao',
            field=models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data Admissão:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dtdemissao',
            field=models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data Demissao:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dtnascimento',
            field=models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data Nascimento:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(max_length=150, verbose_name='Endereço:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.IntegerField(verbose_name='Matricula:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='numero',
            field=models.IntegerField(verbose_name='Número:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Não Definido', 'Não Definido')], max_length=50, verbose_name='Sexo:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.IntegerField(verbose_name='Telefone:'),
        ),
    ]
