# Generated by Django 2.2.12 on 2022-06-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20220501_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(default='', unique=True, verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='descricao',
            field=models.TextField(max_length=500, verbose_name='Descrição:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cliente',
            field=models.CharField(max_length=100, verbose_name='Cliente:'),
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='exercicio',
        ),
        migrations.AddField(
            model_name='ficha',
            name='exercicio',
            field=models.ManyToManyField(to='cadastros.Exercicio'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='funcionario',
            field=models.CharField(max_length=100, verbose_name='Funcionário:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.IntegerField(default='', unique=True, verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.IntegerField(default='', unique=True, verbose_name='Matricula:'),
        ),
    ]
