# Generated by Django 2.2.12 on 2022-06-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20220605_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.IntegerField(max_length=20, null=True, verbose_name='Celular:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.IntegerField(max_length=20, verbose_name='CEP:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(max_length=30, null=True, verbose_name='Complemento:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(default='', max_length=11, unique=True, verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dtnascimento',
            field=models.DateField(help_text='Formato DD/MM/AAAA', max_length=10, verbose_name='Data Nascimento:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=150, null=True, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(max_length=10, verbose_name='Número:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(max_length=20, null=True, verbose_name='Telefone:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='celular',
            field=models.IntegerField(max_length=20, null=True, verbose_name='Celular:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='complemento',
            field=models.CharField(max_length=30, null=True, verbose_name='Complemento:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.IntegerField(default='', max_length=11, unique=True, verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dtdemissao',
            field=models.DateField(help_text='Formato DD/MM/AAAA', null=True, verbose_name='Data Demissao:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(max_length=150, null=True, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.IntegerField(max_length=20, null=True, verbose_name='Telefone:'),
        ),
    ]
