# Generated by Django 2.2.12 on 2022-06-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20220611_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Celular:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dtnascimento',
            field=models.DateField(help_text='DD/MM/AAAA', max_length=10, verbose_name='Data Nascimento:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Telefone:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='celular',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Celular:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='complemento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dtadmissao',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Data Admissão:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dtdemissao',
            field=models.DateField(blank=True, help_text='DD/MM/AAAA', null=True, verbose_name='Data Demissao:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dtnascimento',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Data Nascimento:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Telefone:'),
        ),
    ]
