# Generated by Django 2.2.12 on 2022-06-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_auto_20220612_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(unique=True, verbose_name='CPF:'),
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='exercicio',
        ),
        migrations.AddField(
            model_name='ficha',
            name='exercicio',
            field=models.CharField(default=9, max_length=100, verbose_name='Exercicio:'),
            preserve_default=False,
        ),
    ]
