# Generated by Django 2.2.12 on 2022-06-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_auto_20220622_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='arquivo',
            field=models.FileField(default=8, upload_to='gif/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='arquivo',
            field=models.FileField(default=56, upload_to='gif/'),
            preserve_default=False,
        ),
    ]
